# Generated by Django 2.2.3 on 2019-09-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_academicyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
