SUB_DISTRICTS = [
	['Varkala', 'Attingal', 'Kilimanoor', 'Nedumangad', 'Palode', 'Thiruvananthapuram South', 'Thiruvananthapuram North', 'Kaniapuram', 'Balaramapuram', 'Kattakada', 'Neyyattinkara', 'Parassala'], 
	['Kottarakkara', 'Veliyam', 'Kulakkada', 'Sasthamcotta', 'Chadayamangalam', 'Anchal', 'Punalur', 'Karunagappally', 'Chavara', 'Kollam', 'Chathannoor', 'Kundara'], 
	['Tiruvalla', 'Pullad', 'Aranmula', 'Mallappally', 'Vennikulam', 'Adoor', 'Pandalam', 'Kozhencherry', 'Ranni', 'Pathanamthitta', 'Konni'], 
	['Cherthala', 'Thuravoor', 'Alappuzha', 'Ambalappuzha', 'Haripad', 'Mavelikara', 'Chengannur', 'Kayamkulam', 'Moncompu', 'Thalavady', 'Veliyanadu'], 
	['Ramapuram', 'Kozhuvanal', 'Ettumanoor', 'Pala', 'Erattupetta', 'Kanjrappilly', 'Karukachal', 'Kottayam West', 'Changanacherry', 'Kottayam East', 'Pampady', 'Vaikom', 'Kuravilangadu'], 
	['Arakkulam', 'Thodupuzha', 'Adimaly', 'Kattappana', 'Munnar', 'Peermedu', 'Nedumkandam'], 
	['Aluva', 'Angamaly', 'Kolancherry', 'North Paravur', 'Ernakulam', 'Mattancherry', 'Thripunithura', 'Vypeen', 'Perumbavoor', 'Kothamangalam', 'Kalloorkadu', 'Koothattukulam', 'Muvattupuzha', 'Piravom'], 
	['Cherpu', 'Thrissur East', 'Thrissur West', 'Chalakudy', 'Irinjalakuda', 'Kodungallur', 'Mala', 'Chavakkad', 'Kunnamkulam', 'Mullassery', 'Valappad', 'Wadakancheri'], 
	['Ottapalam', 'Shornur', 'Thrithala', 'Pattambi', 'Alathur', 'Chittur', 'Coyalamannam', 'Kollamghode', 'Palakkad', 'Parali', 'Cherpulassery', 'Mannarkkad'], 
	['Kizhisseri', 'Kondotty', 'Malappuram', 'Manjeri', 'Mankada', 'Perinthalmanna', 'Edappal', 'Kuttippuram', 'Ponnani', 'Tirur', 'Areacode', 'Melattur', 'Nilambur', 'Wandoor', 'Parappanangadi', 'Tanur', 'Vengara'], 
	['Chombala', 'Koyilandy', 'Kunnummal', 'Melady', 'Nadapuram', 'Thodannur', 'Vatakara', 'Kozhikode City', 'Kozhikode Rural', 'Chevayur', 'Feroke', 'Kunnamangalam', 'Mukkam', 'Thamarassery', 'Balussery', 'Perambra', 'Koduvally'], 
	['Vythiri', 'Sulthan Bathery', 'Mananthavady'], 
	['Kannur South', 'Kannur North', 'Irikur', 'Pappinissery', 'Thalassery South', 'Thalassery North', 'Chokli', 'Panoor', 'Kuthuparamba', 'Mattannur', 'Iritty', 'Madayi', 'Thalparamba North', 'Thaliparamba South', 'Payyannur'], 
	['Manjeshwar', 'Kumbla', 'Kasaragod', 'Bekal', 'Hosdurg', 'Chittarikal', 'Cheruvathur'],
]