# Generated by Django 2.2.3 on 2019-09-08 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('classroom', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassRoom')),
                ('interests', models.ManyToManyField(related_name='interested_students', to='quizzes.Subject')),
                ('quizzes', models.ManyToManyField(through='quizzes.TakenQuiz', to='quizzes.Quiz')),
            ],
            managers=[
                ('active_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
