# Generated by Django 2.2.3 on 2019-09-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentmigration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmigration',
            name='status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Passout', 'Pass Out'), ('Failed', 'Failed')], default='Passed', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentmigration',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassRoom'),
        ),
    ]
