# Generated by Django 2.2.3 on 2019-09-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20190911_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='mark',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
