# Generated by Django 2.2.3 on 2019-09-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('classroom', '0003_auto_20190911_0616'),
        ('exams', '0003_auto_20190913_0111'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marks',
            unique_together={('exam', 'subject', 'student')},
        ),
    ]
