# Generated by Django 2.2.3 on 2019-09-11 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('classroom', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AddField(
            model_name='period',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassRoom'),
        ),
        migrations.AddField(
            model_name='period',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.Subject'),
        ),
        migrations.AddField(
            model_name='period',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.School'),
        ),
        migrations.AddField(
            model_name='attendanceclass',
            name='academicyear',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.AcademicYear'),
        ),
        migrations.AddField(
            model_name='attendanceclass',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassRoom'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendanceclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.AttendanceClass'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='classroom',
            unique_together={('school', 'name', 'division')},
        ),
    ]
