# Generated by Django 2.2.3 on 2019-09-11 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('classroom', '0002_auto_20190911_0450'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('school', 'name')},
        ),
    ]
