# Generated by Django 2.2.3 on 2019-08-25 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('schools', '0002_academicyear'),
        ('classroom', '0004_auto_20190710_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('academicyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.AcademicYear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.ClassRoom')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('H', 'Half Day'), ('L', 'Leave'), ('N', 'Not Marked')], default='N', max_length=1)),
                ('attendanceclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.AttendanceClass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
